### ISSUE TITLE
Creating SPNEGO Token

### ISSUE THREAD

**Issue by atishay** [PADL/GSSKit#1]
I am trying to get a SPNEGO Token.
When I use the following attributes in the sample client I get a valid Kerberos Token. 

```
GSSICPassword
GSSICLKDCHostname
GSSCredentialUsage : GSSCredentialUsageInitiate
```

I need a SPNEGO Token. I tried replacing the GSSMechanism with SPNEGOMechanism, I get the following error:

```
unknown mech-code 0 for mech 1 3 6 1 5 5 2, kGSSMinorErrorCode=0, kGSSMechanism=SPNEGO, kGSSMajorErrorCode=1048576, kGSSMechanismOID=1.3.6.1.5.5.2, NSLocalizedDescription= The operation or option is not available
```

Any help would be highly appreciated.

**Comment by lhoward** [comment]
Can duplicate, investigating.

**Comment by lhoward** [comment]
OK, you don't want to acquire a credential for SPNEGOMechanism (that won't work with Heimdal), but instead set:

```
initiatorCtx.mechanism = [GSSMechanism SPNEGOMechanism];
```

and it should work.

**Comment by lhoward** [comment]
i.e. acquire a credential for the mechanism you do actually want to use (e.g. Kerberos).

**Comment by lhoward** [comment]
(I had no idea anyone was actually using this code!) cc @lha
